name: avo_app
description: "AVO Medical Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.9.2

  # State Management
  provider: ^6.1.2

  # Icons & Utils
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  image_picker: ^1.2.1
  google_fonts: ^8.0.2
  intl: ^0.20.2
  flutter_secure_storage: ^10.0.0
  table_calendar: ^3.2.0
  device_preview: ^1.3.1
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  firebase_database: ^12.4.2
  easy_localization: ^3.0.8
  go_router: ^17.2.3
  flutter_bloc: ^9.1.1
  share_plus: ^13.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shimmer_animation: ^2.2.2+1
  font_awesome_flutter: ^11.0.0
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/logo/
    - assets/imgs/onboard/
    - assets/imgs/appointment/
    - assets/imgs/doctor/
    - assets/imgs/profile/
    - assets/imgs/chatbut/
    - assets/imgs/categories/
    - assets/icons/social/
    - assets/svg/appointment/
    - assets/svg/payment/
    - assets/svg/order/
    - assets/translations/
    - assets/svg/logo/
    - assets/svg/roles/